"""empty message

Revision ID: 2ec45b931100
Revises: f48a617131a6
Create Date: 2021-10-12 17:17:10.527577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec45b931100'
down_revision = 'f48a617131a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'gender',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('client', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client', 'weeklyexercise',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('client_gender_key', 'client', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('client_gender_key', 'client', ['gender'])
    op.alter_column('client', 'weeklyexercise',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client', 'gender',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
