"""empty message

Revision ID: 6167b7d0aaaf
Revises: 1c447d73ff87
Create Date: 2021-10-10 18:08:29.074597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6167b7d0aaaf'
down_revision = '1c447d73ff87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('detail', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'detail')
    # ### end Alembic commands ###
