"""empty message

Revision ID: b44b917ac9d7
Revises: 2ec45b931100
Create Date: 2021-10-12 17:23:17.585000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44b917ac9d7'
down_revision = '2ec45b931100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('weekly_exercise', sa.Integer(), nullable=True))
    op.drop_column('client', 'weeklyexercise')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('weeklyexercise', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('client', 'weekly_exercise')
    # ### end Alembic commands ###
